#! /usr/bin/env -S guile

(install-r7rs!)

(import (scheme base)
	(scheme file)
	(yaml))

(vector-for-each 
 (lambda (filename)
   (let* ([in (read-yaml* (open-input-file filename))
           out-filename (string-replace #rx"ya?ml$" filename "toml")
           out (open-output-file (out-filename))
           ])
     )
 (current-command-line-arguments))
