# My massive alias file. Viewer beware.
alias e=$EDITOR
alias ea="$EDITOR ~/.zsh/aliases.zsh"
alias eclimd="/usr/lib/eclipse/eclimd &"
alias ef="$EDITOR ~/.zsh/functions.zsh"
alias ei3="$EDITOR ~/dotfiles/i3/config"
alias ekb="$EDITOR ~/bin/backflip.sxhkd"
alias ls="ls --color=auto -xX"
alias nctl="netctl"
alias nwall="feh --random --bg-fill ~/usr/img/wall"
alias pacupd="sudo pacman -Syu && notify-send 'Pacman' 'System update was successful.'"
alias ping="ping -c 3"
alias pomo="sleep 10m && notify-send 'Pomodoro done!'"
alias reload="source ~/.zshrc"
alias rwall="feh --random --bg-fill ~/usr/img/wall"
alias sctl="systemctl"
alias sctll="systemctl list-units"
alias t="todo.sh"
alias ta="t add"
alias td="t do"
alias tl="t ls"
alias tm="tmux"
alias tns="tmux new-session -s -A "
alias wall="~/.fehbg"
alias xm="xrdb -merge ~/.xrdb.d/main"
alias zreload="source ~/.zshrc"
