#!/bin/sh

. "$HOME/.local/lib/sh/df.sh"

install_link "sh/.shrc" ".shrc"
install_link "sh/.sh.d" ".sh.d"
install_link "sh/.profile" ".profile"
install_link "sh/.dircolors" ".dircolors"

install_link "sh/.local/lib/sh/path.sh" ".local/lib/sh/path.sh"
install_link "sh/.local/lib/sh/preferred_app.sh" ".local/lib/sh/preferred_app.sh"


