
""""""""""""""""""""""""""""""""""""""
" My Vimrc for awesomeness.
""""""""""""""""""""""""""""""""""""""

" Main stuff.

" Perhaps the best map leader.
let mapleader = ","

" Vimrc autoloading.
autocmd! bufwritepost .vimrc source ~/.vimrc

"Automatic syntax highlighting.
syntax enable
filetype plugin indent on
set ofu=syntaxcomplete#Complete
"TODO testing stufffffff

 "autocmd FileType python set omnifunc=pythoncomplete#Complete
 "autocmd FileType c set omnifunc=ccomplete#Complete

" Tags.
set tags+=~/.vim/tags/cpp
set tags+=~/.vim/tags/c_std
set hidden

nnoremap ' `
nnoremap ` '

" Set the mouse to be used in the terminal.
set autoread
" Keeps Vim from autochanging directories.
set noacd

" Different window settings.
"
let Tlist_Use_Right_Window = 1
" Set minibufexplorer to navigate using many different styles.
let g:miniBufExplMapWindowNavVim = 1 
let g:miniBufExplMapWindowNavArrows = 1 
let g:miniBufExplMapCTabSwitchBufs = 1 
let g:miniBufExplModSelTarget = 1

" Sets the tabs for four everything, all spaces.
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

" Load up pathogen and the plugins therein.
call pathogen#infect()

" My leader mappings. It starts out at first with nothing but build stuff.
" Write the current buffer. Super fast and super handy.
nmap <leader>w :w!<cr>

"" Project mappings.
"    Build the current project. Wham. Done.
nmap <leader>b :make<cr>
"    I usually have a rebuild target in my build files that builds everything
"    from scratch, so this is very useful.
nmap <leader>B :make rebuild<cr>

"" Tool mappings.
"    SingleCompile is awesome for really small stuff, like random C tiny programs
"    and Java assignments that only have like one class. 
nmap <leader>c :SCCompile<cr>
nmap <leader>r :SCCompileRun<cr>

nmap <leader>l :TaskList<cr>
nmap <leader>t :TlistToggle<cr>
nmap <leader>p :Project<cr>
nmap <leader>f :NERDTreeToggle<cr>

" Edit the settings with [,s].
nmap <leader>s :e ~/.vimrc<cr>
" Delete the current buffer with [,d].
nmap <leader>d :bd<cr>

" Set to wombat, a very well meaning color scheme. This has to be done after 
" Pathogen does it's thing.

colors obsidian


""" GUI stuff.
set guioptions=aegirLt
