""""""""""""""""""""""""""""""""""""""
" My Vimrc for awesomeness.
" Ben Davenport-Ray
""""""""""""""""""""""""""""""""""""""


call pathogen#infect()



"""" General settings.
syntax enable
filetype plugin indent on
" set ofu=syntaxcomplete#Complete
set nocompatible
set laststatus=2
set encoding=utf-8
set hidden
set autoread
set noacd
set number
set vb
set nocp


" Tags.
set tags+=~/.vim/tags/cpp_tags

" Folding for indented programs.
set foldmethod=syntax
set foldlevel=99

" Sets the tabs for four everything, all spaces.
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab

"""" Auto commands.
au FileType python set omnifunc=pythoncomplete#Complete
au FileType python compiler nose
au FileType c compiler speedunit
au! bufwritepost .vimrc source ~/.vimrc
au BufNewFile,BufRead,BufEnter *.cpp,*.hpp set omnifunc=omni#cpp#complete#Main


" Visual panels and looks
colors solarized
let Tlist_Use_Right_Window = 1
set gfn=Envy\ Code\ R\ 11
" set gfn=Inconsolata\ 12
" set gfn=Anonymous\ Pro\ 12
set guioptions=aegirLt

"""" Mappings.
let mapleader = ","  " Perhaps the best map leader.
nnoremap ' `
nnoremap ` '

" Force to use mappings
noremap <Up> <nop>
noremap <Down> <nop>
noremap <Left> <nop>
noremap <Right> <nop>
inoremap <esc> <nop>

" Set the multibuffer mappings to something more sane.
noremap <c-j> <c-w>j
noremap <c-k> <c-w>k
noremap <c-l> <c-w>l
noremap <c-h> <c-w>h
noremap <c-w> <c-w>w

inoremap <Up> <nop>
inoremap <Down> <nop>
inoremap <Left> <nop>
inoremap <Right> <nop>
inoremap jk <esc>

" Go by graphical lines instead of real ones
noremap j gj
noremap k gk

" Normal mode leader mappings. 
nnoremap <leader>b      :MakeGreen<cr>
nnoremap <leader>br     :MakeGreen("rebuild")<cr>
nnoremap <leader>c      :SCCompile<cr>
nnoremap <leader>d      :bd<cr>
nnoremap <leader>f      :NERDTreeToggle<cr>
nnoremap <leader>p      :Project<cr>
nnoremap <leader>r      :SCCompileRun<cr>
nnoremap <leader>sc     :e ~/dotfiles/vim/bundle/snipmate/snippets/c.snippets
nnoremap <leader>scc    :e ~/dotfiles/vim/bundle/snipmate/snippets/cpp.snippets
nnoremap <leader>v      :e ~/.vimrc<cr>
nnoremap <leader>tg     :TagbarToggle<cr>
nnoremap <leader>tl      <Plug>TaskList
nnoremap <leader>w      :w<cr>
nnoremap <leader>W      :Gwrite<cr>
nnoremap <leader>x      :cwin<cr>

let g:snips_author="Ben Davenport-Ray"
let g:ctrlp_map = '<c-p>'

"""" Configuring C++ tags.

let OmniCpp_NamespaceSearch = 1
let OmniCpp_GlobalScopeSearch = 1
let OmniCpp_ShowAccess = 1
let OmniCpp_ShowPrototypeInAbbr = 1
let OmniCpp_MayCompleteDot = 1
let OmniCpp_MayCompleteArrow = 1
let OmniCpp_MayCompleteScope = 1
let OmniCpp_DefaultNamespaces = ["std", "_GLIBCXX_STD"]

au CursorMovedI,InsertLeave * if pumvisible() == 0|silent! pclose|endif 
set completeopt=menuone,menu,longest,preview

