#! /bin/sh

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true


bspc monitor HDMI-0 -d 1 2 3 4 5
bspc monitor DVI-I-1 -d 6 7 8 9 0

