#! /bin/sh

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config bottom_padding 15

bspc monitor -d main contact shells work chat play media other bg servers

