#!/bin/sh

. "$(dirname "$0")/.local/lib/sh/df.sh"

# Basic path system
PATHS="bin:src:var:doc:org:desk:img:lib:pkg:vid"
IFS=:; for p in $PATHS; do
    mkdir -p "$HOME/$p"
done

mkdir -p "$HOME/.local/lib/sh"

install_link "core/.local/lib/sh/df.sh" ".local/lib/sh/df.sh"

