["colors"]
["colors"."dim"]
"white" = "#B5BFE2"

"cyan" = "#81C8BE"

"magenta" = "#F4B8E4"

"blue" = "#8CAAEE"

"yellow" = "#E5C890"

"green" = "#A6D189"

"red" = "#E78284"

"black" = "#51576D"


["colors"."bright"]
"white" = "#A5ADCE"

"cyan" = "#81C8BE"

"magenta" = "#F4B8E4"

"blue" = "#8CAAEE"

"yellow" = "#E5C890"

"green" = "#A6D189"

"red" = "#E78284"

"black" = "#626880"


["colors"."normal"]
"white" = "#B5BFE2"

"cyan" = "#81C8BE"

"magenta" = "#F4B8E4"

"blue" = "#8CAAEE"

"yellow" = "#E5C890"

"green" = "#A6D189"

"red" = "#E78284"

"black" = "#51576D"


["colors"."selection"]
"background" = "#F2D5CF"

"text" = "#303446"


["colors"."hints"]
["colors"."hints"."end"]
"background" = "#A5ADCE"

"foreground" = "#303446"


["colors"."hints"."start"]
"background" = "#E5C890"

"foreground" = "#303446"



["colors"."search"]
["colors"."search"."footer_bar"]
"background" = "#A5ADCE"

"foreground" = "#303446"


["colors"."search"."focused_match"]
"background" = "#A6D189"

"foreground" = "#303446"


["colors"."search"."matches"]
"background" = "#A5ADCE"

"foreground" = "#303446"



["colors"."vi_mode_cursor"]
"cursor" = "#BABBF1"

"text" = "#303446"


["colors"."cursor"]
"cursor" = "#F2D5CF"

"text" = "#303446"


["colors"."primary"]
"bright_foreground" = "#C6D0F5"

"dim_foreground" = "#C6D0F5"

"foreground" = "#C6D0F5"

"background" = "#303446"


[["colors"."indexed_colors"]]
"color" = "#EF9F76"

"index" = 16


[["colors"."indexed_colors"]]
"color" = "#F2D5CF"

"index" = 17





