" Ben's (Neo)Vimrc.
"vim: set sw=4 ts=4 sts=4 et tw=78 foldmarker={{{,}}} foldlevel=5 foldmethod=marker spell:
"
" Some of this should be split up into different files. 

" Environment
function! WINDOWS()
    return (has("win32") || has("win64")) 
endfunction
function! NVIM()
    return has('nvim')
endfunction

" Neovim setup
if NVIM()
    runtime! plugin/python_setup.vim
    set runtimepath+=/usr/share/vim/vimfiles
    let g:vimdir = "~/.config/nvim"
else
    set nocompatible
    let g:vimdir = "~/.vim"
endif

" Windows setup.
if WINDOWS()
    let g:vimdir = "~/vimfiles"
endif

" Plugins {{{
call plug#begin(g:vimdir . "/bundle")

" Basic improvements"{{{
Plug 'sjl/gundo.vim'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-repeat'
Plug 'jacquesbh/vim-showmarks'
Plug 'tpope/vim-eunuch' 
Plug 'takac/vim-hardtime'
Plug 'sheerun/vim-polyglot'
 
if NVIM()
    Plug 'laserswald/iron.nvim'
endif
"}}}

" Tagging plugins.{{{
Plug 'Shougo/vimproc.vim', {'do': 'make'} | Plug 'Shougo/unite.vim' | Plug 'Shougo/neoinclude.vim' | Plug 'tsukkee/unite-tag'
if NVIM()
    Plug 'fntlnz/atags.vim'
else
    Plug 'xolox/vim-misc' | Plug 'xolox/vim-easytags'
endif
"}}}

" Completion plugins."{{{
Plug 'ervandew/supertab'
if NVIM()
    Plug 'Shougo/deoplete.nvim'
else 
    Plug 'Shougo/neocomplete.vim'
endif
Plug 'SirVer/ultisnips' | Plug 'honza/vim-snippets'
"}}}

" Eye Candy {{{
Plug 'itchyny/lightline.vim'
Plug 'bling/vim-bufferline'
Plug 'kien/rainbow_parentheses.vim'
"}}}

" Themes"{{{
Plug 'laserswald/chameleon.vim'
Plug 'AlessandroYorba/Alduin'
Plug 'nanotech/jellybeans.vim'
Plug 'altercation/vim-colors-solarized'
Plug 'noahfrederick/vim-noctu'
Plug 'chriskempson/base16-vim'
Plug 'fxn/vim-monochrome'
"}}}

" REPL plugins"{{{
Plug 'jpalardy/vim-slime'
"}}}

" Databases."{{{
Plug 'vim-scripts/dbext.vim'
"}}}

" File opening and management plugins
Plug 'tpope/vim-fugitive'
Plug 'justinmk/vim-dirvish' 
Plug 'tpope/vim-projectionist'

" Movement plugins
Plug 'godlygeek/tabular'
if ! NVIM()
    " Plug 'christoomey/vim-tmux-navigator'
endif

" Building and compiling plugins
" TODO: Switch to my fork
" Plug 'reinh/vim-makegreen'
if NVIM()
    Plug 'benekastah/neomake'
else
    Plug 'tpope/vim-dispatch'
    Plug 'scrooloose/syntastic'
endif


Plug 'junegunn/fzf', {'dir': '~/.fzf', 'do': './install --all'}

" Compiler settings.
Plug 'JalaiAmitahl/maven-compiler.vim', {'for' : 'java'}

" Debugging
Plug 'joonty/vdebug'

" Filetype specific plugins"{{{

    " Organization {{{
    Plug 'nelstrom/vim-markdown-folding', {'for' : 'markdown'}
    Plug 'mattn/emmet-vim', {'for': 'html'}
    Plug 'freitass/todo.txt-vim'
    Plug 'jceb/vim-orgmode'
    " }}}

    " C {{{
    Plug 'vim-scripts/cscope.vim', {'for' : 'c'}
    "}}}

    " C# {{{
    Plug 'OmniSharp/omnisharp-vim', {'for' : 'cs'}
    "}}}

    " PHP {{{
    Plug 'StanAngeloff/php.vim', {'for' : 'php'}
    Plug 'shawncplus/phpcomplete.vim', {'for' : 'php'}
    Plug 'rayburgemeestre/phpfolding.vim', {'for' : 'php'}
    "}}}

" Golang
Plug 'fatih/vim-go'

"}}}
"
call plug#end()
" 1}}}

" Options

" Essentials. This should be moved to some 'core.vim' thing
syntax enable
filetype plugin indent on

" General mapping settings.
let mapleader = ' '  " Perhaps the best map leader.
let maplocalleader = '\'

" Make jk escape to normal mode
inoremap jk <esc>
vnoremap jk <esc>


" My own custom functions."{{{
function! SwitchColors()
    if &background == "dark"
        exec "set background=light"
    else
        exec "set background=dark"
    endif
    exec "colorscheme ".g:colors_name
endfunction
command! SwitchColors call SwitchColors()

function! TitleCase()
    let l:words = split(getline('.'), '\W')
    let l:chg = ""
    for word in l:words
        " Get the first letter
        let l:head = toupper(strpart(word, 0, 1))
        let l:tail = strpart(word, 1)
        let l:chg .= l:head . l:tail . " "
    endfor
    call setline('.', l:chg)
endfunction
command! TitleCase call TitleCase()

function! SplitLine(pattern)
    " Split the current line by the pattern
    let l:words = split(getline('.'), a:pattern)
    " Append the strings as new lines
    call append(getline('.'), l:words)
endfunction
"}}}
   

