alias c=cd
alias df="e ~/etc"
alias ds=dirs
alias dvtm="dvtm -m "
alias ea="e ~/.sh.d/aliases.sh"
alias eclimd="/usr/lib/eclipse/eclimd &"
alias edit=$EDITOR
alias e=$EDITOR
alias ei3="$EDITOR ~/etc/i3/.i3/config"
# Aliases
alias exm="$EDITOR ~/etc/xmonad/.xmonad/xmonad.hs"
alias h='history'
alias j='jobs -l'
alias la="ls -a"
alias ll="ls -l"
alias l=ls
alias ls="ls --color=auto -xX"
alias nctl="netctl"
alias o=popd
alias p9="drawterm -c gibson.gnot.club -a gibson.gnot.club -u lazr"
alias ping="ping -c 3"
alias pomo="sleep 10m && notify-send 'Pomodoro done!'"
alias p=pushd
alias randw=rwall
alias refresh="sudo pacman -Syy"
alias reload="source ~/.profile"
alias rl=reload
alias rwall="feh --random --bg-fill ~/usr/img/wall"
alias sctll="systemctl list-units"
alias sctl="systemctl"
alias ta="t add"
alias td="t do"
alias tl="t ls"
alias tm="tmux"
alias tmux="tmux -2"
alias tns="tmux new-session -s -A "
alias t="todo.sh"
alias update="sudo pacman -Syu && notify-send 'Pacman' 'System update was successful.'"
alias wall="~/.fehbg"
alias xm="xrdb -merge ~/.xrdb.d/main"
