alias c=cd
alias ds=dirs
alias p=pushd
alias o=popd
alias ea="$EDITOR ~/.sh.d/aliases.sh"
alias eclimd="/usr/lib/eclipse/eclimd &"
alias e=$EDITOR
alias ei3="$EDITOR ~/dotfiles/i3/config"
alias la="ls -a"
alias ls="ls --color=auto -xX"
alias ll="ls -l"
alias l=ls
alias nctl="netctl"
alias p9="drawterm -c gibson.gnot.club -a gibson.gnot.club -u lazr"
alias ping="ping -c 3"
alias pomo="sleep 10m && notify-send 'Pomodoro done!'"
alias refresh="sudo pacman -Syy"
alias reload="source ~/.shrc"
alias rwall="feh --random --bg-fill ~/usr/img/wall"
alias sctll="systemctl list-units"
alias sctl="systemctl"
alias ta="t add"
alias td="t do"
alias tl="t ls"
alias tm="tmux"
alias tmux="tmux -2"
alias tns="tmux new-session -s -A "
alias t="todo.sh"
alias update="sudo pacman -Syu && notify-send 'Pacman' 'System update was successful.'"
alias wall="~/.fehbg"
alias xm="xrdb -merge ~/.xrdb.d/main"
