# Mappings
map global user w :write<ret>
map global user s :send-text<ret>
map global user S <a-s>
map global goto b <esc>:buffer<space>

set global tabstop 4
set global indentwidth 4

define-command -allow-override fzf %{ %sh{
	# Suspend kak
	kill -STOP $kak_client_pid
	echo "hello"
	fzf
	echo "eval -client '$kak_client' 'edit! $selected_file'"| kak -p ${kak_session}
	kill -CONT $kak_client_pid
}}

def find -params 1 -shell-candidates %{find -type f} %{edit %arg{1}}
