#! /bin/sh
HCONFIG_PROJECTS="
$HOME/src/c/dwm
$HOME/src/c/st
$HOME/src/c/tabbed
$HOME/src/c/dmenu
"

for p in $HCONFIG_PROJECTS; do 
    cd $p
    make clean
    make && sudo make install
    cd -
done
