selenized:
    primary:
      background: &background '181818ff'
      foreground: &foreground 'b9b9b9ff'
    normal:
      black:   '252525ff'
      red:     'ed4a46ff'
      green:   '70b433ff'
      yellow:  'dbb32dff'
      blue:    '368aebff'
      magenta: 'eb6eb7ff'
      cyan:    '3fc5b7ff'
      white:   '777777ff'
    bright:
      black:  &tag-unfocused '3b3b3bff'
      red:     'ff5e56ff'
      green:   '83c746ff'
      yellow:  'efc541ff'
      blue:   &tag-invisible '4f9cfeff'
      magenta: 'ff81caff'
      cyan:   &tag-focused '56d8c9ff'
      white:   'dededeff'


shared: 
	on-tag-click: &shared-on-tag-click
		left: sh -c 'riverctl set-focused-tags $((1 << ({id} - 1)))'
		right: sh -c 'riverctl toggle-focused-tags $((1 << ({id} - 1)))'

	river-tags: &shared-river-tags
	    map:
	        tag: occupied
	        values:
	            false: {empty: {}}
	            true:
	                map:
	                    tag: state
	                    default:
	                        string:
	                            margin: 5
	                            text: "{id}"
	                            foreground: *foreground
	                            on-click: *on-tag-click 
	                    values:
	                        unfocused:
	                            string:
	                                margin: 5
	                                text: "{id}"
	                                foreground: *tag-unfocused
	                                on-click: *on-tag-click
	                        focused:
	                            string:
	                                margin: 5
	                                text: "{id}"
	                                foreground: *tag-focused
	                                on-click: *on-tag-click
	                        invisible:
	                            string:
	                                margin: 5
	                                text: "{id}"
	                                foreground: *tag-invisible
	                                on-click: *on-tag-click
    


bar:
    height: 32
    location: top
    background: *foreground
    foreground: *background
    font: "Fira Code Retina:size=24"
    monitor: eDP-1
    left:
        - river:
            title: {empty: {}}
            content: *shared-river-tags
    center:
        - river:
            title: {string: { text: "{title}"}}
            content: {empty: {}}
    right:
        - battery:
            name: BAT0
            poll-interval: 30
            content:
                string: {text: "battery {capacity}%"}
        - alsa:
            card: PipeWire
            mixer: Master
            content: {string: {text: "vol {volume}"}}
        - clock:
            content:
                string:
                    text: "| {date} - {time}"

