# Lines configured by zsh-newuser-install
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory autocd extendedglob nomatch
bindkey -v
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/ben/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall

autoload -U colors && colors
autoload -Uz vcs_info
zstyle ':vcs_info:*' enable git svn
zstyle ':vcs_info:*' check-for-changes true
precmd(){
    vcs_info
}

zstyle ':vcs_info:git*' formats " [%s %{$fg[white]%}%r%{$reset_color%} %{$fg[yellow]%}%b%{$reset_color%} %m%{$fg[red]%}%u%{$reset_color%}%{$fg[magenta]%}%c%{$reset_color%}]"
setopt prompt_subst
PROMPT='%{$fg[green]%}%n%{$reset_color%}%# at %{$fg[blue]%}%m%{$reset_color%}${vcs_info_msg_0_}> '
RPROMPT='%{$fg[yellow]%}%~%{$reset_color%}'
export EDITOR="vim"
source "/home/ben/dotfiles/zsh/aliases.zsh"
source "/home/ben/dotfiles/zsh/functions.zsh"
eval "$(fasd --init auto)"

