#!/bin/sh

action=$1

shift

test "$action" = "usage" && {
    echo "   everything:"
    echo "     show all tasks in all todo txt files in the todo.sh directory."
    echo ""
    exit 
}

for f in ${TODO_DIR}/*todo.txt; do
	base=$(basename $f)
	prefix=$(echo ${base%%.*} | tr '[:lower:]' '[:upper:]')
    TODOTXT_VERBOSE=0 ${TODO_FULL_SH} -n listfile $f $@ | sed "s~^~${prefix}: ~"
done

