#!/bin/sh
# My River configuration file.

set -e

# This variable is set when called from `river-reload`.
# Guard things that should not be launched twice here
: ${RIVERCTL_RELOADING:=}

# run_services SERVICE_DIRECTORY
# Run the `runit` services needed to provide a full desktop with River.
run_services()
{
    service_directory=$1

    if ! pgrep "runsvdir $service_directory"
    then
	runsvdir $service_directory &
    fi
}

#
# LOGGING
#

LOG_PATH_FMT="${XDG_STATE_HOME}/river/init.%i.log"
LOG_KEEP_AMOUNT=10

# rotate_log
# Rotates the logs for this River instance
rotate_log()
{
    # Create the logging directory
    mkdir -p "$XDG_STATE_HOME/river"

    # Remove the oldest log.
    rm -f "$(printf $LOG_PATH_FMT $LOG_KEEP_AMOUNT)"

    # For each log file in the directory, we move it to the next slot
    #
    # We need to do it backwards so that we don't accidentally overwrite
    # an older log with a newer log.
    for i in $(seq $((LOG_KEEP_AMOUNT - 1)) -1 0)
    do	
	log_name=$(printf $LOG_PATH_FMT $i)
	if [ -f "$log_name" ]
	then
	    mv "$log_name" "$( printf $LOG_PATH_FMT $((i + 1)) )"
	fi
    done
}

rotate_log
exec 2>&1 >$(printf $LOG_PATH_FMT 0)

##
## Desktop and laptop events.
##

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive
    riverctl map $mode None XF86Eject spawn "eject -T"

    # Control system volume uing `pactl` which should be installed generally
    riverctl map -repeat $mode None XF86AudioRaiseVolume  spawn "pactl set-sink-volume @DEFAULT_SINK@ +5%"
    riverctl map -repeat $mode None XF86AudioLowerVolume  spawn "pactl set-sink-volume @DEFAULT_SINK@ -5%"
    riverctl map $mode None XF86AudioMute         spawn "pactl set-sink-mute @DEFAULT_SINK@ toggle"
    riverctl map $mode None XF86AudioMicMute      spawn "pactl set-source-mute @DEFAULT_SOURCE@ toggle"

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioMedia spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPlay  spawn "playerctl play-pause"
    riverctl map $mode None XF86AudioPrev  spawn "playerctl previous"
    riverctl map $mode None XF86AudioNext  spawn "playerctl next"

    # Control screen backlight brighness with brightnessctl
    riverctl map -repeat $mode None XF86MonBrightnessUp   spawn "brightnessctl set +10%"
    riverctl map -repeat $mode None XF86MonBrightnessDown spawn "brightnessctl set 10%-"

    # Screenshots 
    riverctl map $mode None Print spawn "$HOME/bin/screenshot-tool"
    riverctl map $mode Control Print spawn "$HOME/bin/screenshot-tool region"

    riverctl map-switch $mode lid close spawn "systemctl sleep"
    # riverctl map-switch $mode lid open
done

##
## Keybinding setup.
##

# Use the "logo" key as the primary modifier
mod="Mod4"

# Custom modifier on the right side of my Ergodox
hyper="Mod4+Shift+Mod1+Control"

# Custom modifier on the left side of my Ergodox
meh="Shift+Mod1+Control"

##
## Preferred applications
##

# Abstract terminal so I don't have to reload River just to switch terms
term="$HOME/bin/favorite-terminal"
riverctl map normal $mod+Shift Return spawn "$term"
riverctl map normal $hyper Return spawn "$term"

# term_instance COMMAND
# Launch COMMAND in a new terminal instance.
term_instance () {
    echo $term '-c' $1 $1
}
chatcmd=$(term_instance "wee")
fmcmd=$(term_instance "ranger")
scratchpadcmd=$(term_instance "scratchpad")
mailcmd=$(term_instance "neomutt")

# Choose an XDG Desktop application.
riverctl map normal $mod Space spawn "wofi --show drun"

# Choose a command-line application.
riverctl map normal $mod+Shift Space spawn "wofi --show run"

# Command to launch a browser.
browsercmd="$HOME/bin/favorite-browser"

# Command to search the web for a query.
searchcmd="$HOME/bin/web-search"

secretscmd="passmenu --type"
riverctl map normal $meh S spawn "$secretscmd"

# Mod+C to close the focused view, just like dwm
riverctl map normal $mod C close

# Security commands
lockcmd="swaylock"
riverctl map normal $mod Q spawn "$lockcmd"
riverctl map normal $mod+Shift Q spawn "pkill --signal SIGHUP runsvdir; riverctl exit"

# Mod+J and Mod+K to focus the next/previous view in the layout stack
riverctl map normal $mod J focus-view down
riverctl map normal $mod K focus-view up

# Mod+Shift+J and Mod+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal $mod+Shift J swap next
riverctl map normal $mod+Shift K swap previous

# Mod+Period and Mod+Comma to focus the next/previous output
riverctl map normal $mod Comma focus-output left
riverctl map normal $mod Period focus-output right

# Mod+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal $mod+Shift Comma send-to-output left
riverctl map normal $mod+Shift Period send-to-output right

# Mod+Return to bump the focused view to the top of the layout stack
riverctl map normal $mod Return zoom

# Mod+H and Mod+L to decrease/increase the main_factor value of rivertile by 0.05
riverctl map normal $mod H send-layout-cmd rivertile "main-ratio -0.05"
riverctl map normal $mod L send-layout-cmd rivertile "main-ratio +0.05"

# Mod+Shift+H and Mod+Shift+L to increment/decrement the main_count value of rivertile.
riverctl map normal $mod+Shift H send-layout-cmd rivertile "main-count +1"
riverctl map normal $mod+Shift L send-layout-cmd rivertile "main-count -1"

# Mod+Alt+{H,J,K,L} to move views
riverctl map normal $mod+Mod1 H move left 100
riverctl map normal $mod+Mod1 J move down 100
riverctl map normal $mod+Mod1 K move up 100
riverctl map normal $mod+Mod1 L move right 100

# Mod+Alt+Control+{H,J,K,L} to snap views to screen edges
riverctl map normal $mod+Mod1+Control H snap left
riverctl map normal $mod+Mod1+Control J snap down
riverctl map normal $mod+Mod1+Control K snap up
riverctl map normal $mod+Mod1+Control L snap right

# Mod+Alt+Shif+{H,J,K,L} to resize views
riverctl map normal $mod+Mod1+Shift H resize horizontal -100
riverctl map normal $mod+Mod1+Shift J resize vertical 100
riverctl map normal $mod+Mod1+Shift K resize vertical -100
riverctl map normal $mod+Mod1+Shift L resize horizontal 100

# Mod + Left Mouse Button to move views
riverctl map-pointer normal $mod BTN_LEFT move-view

# Mod + Right Mouse Button to resize views
riverctl map-pointer normal $mod BTN_RIGHT resize-view

for i in $(seq 1 9)
do
    tags=$((1 << ($i - 1)))

    # Mod+[1-9] to focus tag [0-8]
    riverctl map normal $mod $i set-focused-tags $tags

    # Mod+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal $mod+Shift $i set-view-tags $tags

    # Mod+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal $mod+Control $i toggle-focused-tags $tags

    # Mod+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal $mod+Shift+Control $i toggle-view-tags $tags
done

# Mod+0 to focus all tags
# Mod+Shift+0 to tag focused view with all tags
all_tags=$(((1 << (32)) - 1))
riverctl map normal $mod 0 set-focused-tags $all_tags
riverctl map normal $mod+Shift 0 set-view-tags $all_tags

# Mod+Space to toggle float
riverctl map normal $mod F toggle-float

# Mod+F to toggle fullscreen
riverctl map normal $mod+Shift F toggle-fullscreen

# Mod+{Up,Right,Down,Left} to change layout orientation
riverctl map normal $mod Up    send-layout-cmd rivertile "main-location top"
riverctl map normal $mod Right send-layout-cmd rivertile "main-location right"
riverctl map normal $mod Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal $mod Left  send-layout-cmd rivertile "main-location left"

riverctl map normal $mod+Shift Up    send-layout-cmd rivertile "view-padding +1"
riverctl map normal $mod+Shift Down  send-layout-cmd rivertile "view-padding -1"
riverctl map normal $mod+Shift Left  send-layout-cmd rivertile "outer-padding +1"
riverctl map normal $mod+Shift Right send-layout-cmd rivertile "outer-padding -1"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Mod+F11 to enter passthrough mode
riverctl map normal $mod F11 enter-mode passthrough

# Mod+F11 to return to normal mode
riverctl map passthrough $mod F11 enter-mode normal

# Set repeat rate
riverctl set-repeat 50 300

# Set app-ids of views which should float
riverctl rule-add -app-id "float" float
riverctl rule-add -app-id "popup" float

# Set app-ids of views which should use client side decorations
riverctl rule-add -app-id "gedit" csd
riverctl rule-add -app-id "epiphany" csd

riverctl rule-del -app-id "nwggrid" csd
riverctl rule-del -app-id "emacs" csd

riverctl focus-follows-cursor normal

if ! [ $RIVERCTL_RELOADING ]; then
    dbus-update-activation-environment DISPLAY WAYLAND_DISPLAY XDG_SESSION_TYPE XDG_CURRENT_DESKTOP=river &
    systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP DISPLAY XDG_SESSION_TYPE

    swayidle -w &

    # Run some desktop services

    # Status bar 
    waybar &

    # Desktop background.
    swaybg -i ~/img/wallpaper &

    # 
    kanshi &
    dunst &

    # Optional services
    command -v telegram-desktop && telegram-desktop &
    command -v foot && foot --server &
    command -v dex && dex -a &
fi

# Set and exec into the default layout generator, rivertile.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile &

